// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atufabjdkajsjkgeqsdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0dWZhYmpka2Fqc2prZ2Vxc2RyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NDQyMDgsImV4cCI6MjA3MzMyMDIwOH0.Aq5uNR59zriojm7rGd92Ll3uMe1p2IeuwoYe1jnfZUA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});